import createClient from "openapi-fetch";
import type { paths, components } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://inctagram.work" });


client.GET('/api/v1/public-user').then(result => {
    console.log(result.data!.totalCount)
})