import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {ReduxWrapper} from "@/store/ReduxWrapper";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <header>HEADER

      <ul>
        <li>
          <Link href={'/auth/login'}>LOGIN</Link>
        </li>
        <li>
          <Link href={'/auth/registration'} prefetch={false}>Registration</Link>
        </li>
        <li>
          <Link href={'/auth/registration/confirmation?code=123342342122131'} prefetch={false}>Confirmation</Link>
        </li>
        <li>
          <Link href={'/pokemons'} prefetch={false}>pokemons</Link>
        </li>
      </ul>
      <hr/>
    </header>
    <ReduxWrapper>
      {children}
    </ReduxWrapper>
    <footer>
      <hr/>
      FOOTER
    </footer>
    </body>
    </html>
  );
}
