import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "https://inctagram.work" });


//const response = await client.GET('/api/v1/users/profile')

//response.data?.avatars.map(a => a.url)